name: CMake Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up EVDS_APIKEY environment variable from GitHub Secrets
    - name: Set up EVDS API Key
      run: echo "EVDS_APIKEY=${{ secrets.EVDS_APIKEY }}" >> $GITHUB_ENV

    # Install dependencies, including libcurl
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev


    - name: Configure CMake
      # run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      run : mkdir build ; cd build ; cmake .. ; make 

    # - name: Build
    #   run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test 
      run: ${{github.workspace}}/build/bin/evdscpp bie_yssk  --test true
      

    # - name: Test
    #   working-directory: ${{github.workspace}}/build
    #   run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
